### ISSUE TITLE
Playnite Default Glossi Configuration does not ignore Steam sourced Games

### ISSUE THREAD

**Issue by RamazanKara** [LemmusLemmus/GlosSI-Integration-Playnite#11]
Games with Source set to Steam still are triggering the default Glossi Shortcut. These should not trigger any shortcut as they are run directly from Steam

**Comment by RamazanKara** [comment]
Version 1.0.3

**Comment by LemmusLemmus** [comment]
Oops, that sounds like a glaring oversight on my part. Luckily, it should be very easy to fix.

**Comment by LemmusLemmus** [comment]
The issue should hopefully be fixed in v1.0.4, can you verify that it has been fixed?

**Comment by RamazanKara** [comment]
Seems fixed. Thank you for your quick reaction to this issue.
