### ISSUE TITLE
Extension doesn't work with Pokémon games

### ISSUE THREAD

**Issue by giodude12** [LemmusLemmus/GlosSI-Integration-Playnite#13]
This might sound weird, but I've been able to make a dedicated glosi shortcut for any game in my library. Pokémon specifically though doesn't launch glosi when I make a custom profile for them. My guess is the accent on the é, maybe that's to blame? This can't be a coincidence.

EDIT: Can confirm renaming Pokémon Black to Pokemon Black fixes this issue

**Comment by LemmusLemmus** [comment]
Oh no, I thought that issue had been fixed... What version of GlosSI are you using?

**Comment by giodude12** [comment]
using 0.1.0.2

**Comment by LemmusLemmus** [comment]
Good catch! It seems to be an issue with the Steam game ID generation from the game names. The ID used to launch the Steam shortcut apparently has to be generated from the name of the game as it is represented in .vdf format. Currently, no name containing Unicode characters will work properly. It should hopefully not be too hard to fix.

**Comment by giodude12** [comment]
Thanks! Glad you figured it out, this was driving me crazy.

**Comment by LemmusLemmus** [comment]
This should now be fixed in the latest version! Please let me know if it still does not work properly.
