### ISSUE TITLE
shortcuts.vdf appearently missing/incorrect location

### ISSUE THREAD

**Issue by Raik176** [LemmusLemmus/GlosSI-Integration-Playnite#29]
So, im guessing this is caused by the fact that i installed steam using scoop which means that the file is stored at `C:\Users\RHM\scoop\apps\steam\current\userdata\846759254\config\shortcuts.vdf` instead of the default location. Is there anything i can do?

**Comment by LemmusLemmus** [comment]
Yep, you are correct! The extension should be able to handle Steam being located in different directories, but it unfortunately checks if the path that `shortcuts.vdf` is located in includes `steam\userdata`, which apparently is not the case in your path (there is a `current` directory in-between for some reason). The reason it checks the path in the first place is simply to prevent users from creating the `shortcuts.vdf` file anywhere and expecting it to work.

I will fix the code and get back to you! Thanks for reporting the issue and identifying its cause!

If you do not mind, I will fix the code in the experimental version of the extension <sub>(with new features, such as support for launching the shortcuts from Steam and quick switching between Steam Big Picture mode and Playnite's fullscreen mode)</sub> and upload the Playnite .pext file here (which you can then drag and drop into Playnite or run directly). It should hopefully provide a better experience, but please do report any additional bugs you find!

**Comment by LemmusLemmus** [comment]
@Raik176 This version of the extension should hopefully fix the issue: [GlosSIIntegration 1.1.2+ experimental_v2.zip](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/13787401/GlosSIIntegration.1.1.2%2B.experimental_v2.zip).

If you find any problems/bugs (or if you do not), please let me know! I intend to release this version as the next update if there are no problems with it.

**Comment by Raik176** [comment]
Seems to be working fine, haven't found a single bug yet.
