### ISSUE TITLE
Closing the shortcut via the Steam overlay should also close the game.

### ISSUE THREAD

**Issue by LemmusLemmus** [LemmusLemmus/GlosSI-Integration-Playnite#3]
Currently, when exiting the GlosSI shortcut via the Steam overlay only the overlay is closed.  The game associated with the overlay should preferably also be closed.

Whether or not the game should be forcefully closed is another question. Perhaps a tag could be used to let the user decide for themselves which games need to be killed?

**Comment by Alia5** [comment]
Should be done in GlosSI tbh  
Probably will be soon-ish™

**Comment by LemmusLemmus** [comment]
Support for this has been added in the latest version! Please let me know if something is not working properly or if anyone wishes to see more features related to this (for example, there is currently no way to choose whether the game should simply be killed or if the extension should attempt to close it normally).
