### ISSUE TITLE
Broken input on non-Steam games even after uninstall

### ISSUE THREAD

**Issue by sozasax** [LemmusLemmus/GlosSI-Integration-Playnite#31]
Hi,

As the post title says, I believe that this program is causing issues as far as my non-Steam games detecting my controller input—this was non-existent prior to installing both the program and extension. I've tried removing the program, all relevant files in my C: drive, replacing the shortcuts.vdf... Steam games work fine with Steam Input. But save for emulators, I can't get any inputs to work on games from other platforms (EGS, GOG, Ubisoft, etc.). Any assistance would be appreciated, because I have no idea what what went wrong to begin with! Thanks in advance.

Edit: There are some other issues I've noticed which may or may not be useful information. I found out that this was an issue when trying to launch Splinter Cell. The game will boot, but a white window will quickly flash and clicking the Windows key or alt-tabbing will cause it to hang for a moment before either crashing or advancing to the main menu. Keyboard and mouse inputs work fine. It's just my controller that is affected.

**Comment by sozasax** [comment]
Hi again, it turns out this was an issue with a different program. Sorry if the first post came off too accusatory, I was more concerned than angry that my device stopped working on most of my games... Have a good one.

**Comment by LemmusLemmus** [comment]
No worries!

Concerning Steam (input), this extension only modifies the `shortcuts.vdf` file (albeit indirectly, via GlosSI command line arguments). It is GlosSI and its dependencies HidHide and ViGEm that does the advanced controller input stuff :).

Nice to hear that you found the problem (and that it was not caused by this extension ;) )!
