### ISSUE TITLE
Playnite losing focus when GlosSi UI enabled, GlosSi Integration extenstion error when GlosSi UI disabled

### ISSUE THREAD

**Issue by billybruiser** [LemmusLemmus/GlosSI-Integration-Playnite#9]
When you launch a game or Playnite in fullscreen with the extension, Playnite loses focus because of the Glossi/Steam overlay, so you have to use a mouse to regain focus of Playnite.  
If you disable the Glossi/Steam overlay in GlosSiConfig, the GlosSi Integration gives a warning message every time it starts that "GlosSi Integration Failed to close the Steam Overlay in time."  This happens every time you start Playnite in fullscreen, and every time you exit a game back to Playnite, so it's not a very smooth integration as is.

Could you disable the warning message or somehow cause Playnite to regain focus?  I know there's the option in Playnite for the home button to do that, but that's obviously not useful if you are actually wanting to use the Steam Overlay.

**Comment by LemmusLemmus** [comment]
Well that's not good. Both solutions you suggested should work, but the "failed to close in time" message seems to suggest an underlying problem which should be fixed (probably something I overlooked).

Two quick questions:
- Which version of GlosSI are you using?
- Are you using the Playnite overlay feature?

**Comment by billybruiser** [comment]
It's version 0.0.9.1 that was released yesterday.  I had the Win10 crash it fixed.

Yes, I was using the Playnite overlay to start GlosSi when Playnite Fullscreen was used and the Playnite Overlay option.  All other options were unchecked.  

I uploaded a video of what I see.  The GlosSi status windows steals focus from Playnite and Playnite doesn't get it back until I click it with the mouse. https://youtu.be/8pRgogFA1Dw

**Comment by LemmusLemmus** [comment]
I see the problem.

Side note: 
If you only use the Playnite overlay option and nothing else you won't have any overlay in-game (the Playnite overlay option is only meant as a separate overlay for Playnite itself). You would probably also want to use the default overlay option and/or "add integration" to individual games. If you only plan to use the same overlay (and the same controller configuration) across all games you might as well just use GlosSI without this extension.

**Comment by LemmusLemmus** [comment]
Both issues should hopefully be fixed in the latest version! Can you check if it has been fixed on your end?

**Comment by billybruiser** [comment]
This seems to be working now.  I tested it out in a variety of ways and nothing broke it.  

There was one buggy thing, but I think it's probably more of a GlosSi problem than the Playnite integration.

I tested using a GOG game.  When I brought up the steam overlay and then tried to adjust controller configuration, the controller configuration window was not in focus and I had to alt tab to it to adjust controls.  To my amateur eye it seems like a thing that is not really fixable with how everything's implemented.

**Comment by LemmusLemmus** [comment]
Great!

Regarding the controller configuration window not being in focus, were you by any chance in the non-big picture mode overlay when you opened the controller configuration window? If so, that's normal Steam behaviour AFAIK. Otherwise, it sounds very weird, since you were able to open the Steam overlay in the first place. It is most likely a problem related to GlosSI itself, so if the issue occurs again, consider reporting it on GitHub or with a message in the GlosSI [Discord](https://discord.com/invite/T9b4D5y) server.

**Comment by billybruiser** [comment]
Actually that was it.  Silly me unchecked that as some point I guess.  It's working great with it.  Thanks for the help.
